### PR TITLE
update

### PR DESCRIPTION
**Pull request by johnfg12**

### CODE REVIEW

**Comment by chuggafan** [comment]
John, please, for my sanity, how do you NOT tell icy that bonerock is meant to be **PILLARS, NOT TREES**

**Comment by johnfg12** [comment]
u dont :P icy does what icy wants dont try to control him hes like a free spirit he goes off does what he wants and ignores everyone lel

**Comment by chuggafan** [comment]
remind me why you included your own mod in the pack when quadrum had it's own generation that worked fine btw?

**Comment by johnfg12** [comment]
the general idea was to switch over to this mod and get rid of quandrum and extrabiomes

**Comment by chuggafan** [comment]
and remind me how that worked out?

**Comment by chuggafan** [comment]
this is why trying to fix what ain't broken is a badddd idea

**Comment by johnfg12** [comment]
well using your logic we wouldn't have electricity :P i try to constantly improve things

**Comment by chuggafan** [comment]
electricity is an accidental discovery, researched thoroughly then it was found to be a massive improvement that fixed stuff wrong with oil, so it was used

**Comment by johnfg12** [comment]
the point was if experiments didn't happen stuff wouldn't improve

**Pull request merged**
